### ISSUE TITLE
dll mising

### ISSUE THREAD

**Issue by limelect** [TOSUN-Shanghai/TSMasterDemos#3]
I give up. It seems you are a beginner.
With all due respect.
Now a Dll is missing TSmaster.dll
compiling it in other languages does not suit
a Delphi programmer.
So unless you are perfect I give up.

I am with Delphi since number 1 I just
having fun with you guys.
I do not really need to learn except see what you did.

**Comment by freshhope** [comment]
You have everything after TSMaster is installed, this repository is just for backup, why not see help and demo in TSMaster first?

**Comment by limelect** [comment]
Never open an exe which i do not know.
good luck

**Comment by freshhope** [comment]
Calling sdk without TSMaster installed is not allowed.
