### ISSUE TITLE
TSMasterAPI.py load dll failed

### ISSUE THREAD

**Issue by lijieamd** [TOSUN-Shanghai/TSMasterDemos#5]
I'm trying to use the python example but it seems as that the TSMaster.dll is not successfully loaded.
I debug into the TSMasterAPI.py, and the error log is:
`Could not load the TOSUN DLL from 'C:\Program Files (x86)\TOSUN\TSMaster\bin/TSMaster.dll'. Error: [WinError 193] %1 is not a valid Win32 application`

I checked the source code here,
```
dll_path = os.path.split(dll_path)[0] + '/TSMaster.dll'
dll = WinDLL(dll_path)
```
 it uses the windows register key to find the dll file, I double check the path and dll file, it is exactly there, and I also load another dll file with WinDLL() function to check the load function, it is ok.

my TSMASTER version is 2023.3.29.85 (TSMaster.dll version is the same)

**Comment by sy950915** [comment]
You are using TSMaster version 2023.3.29, which at the time only supported the x86 version. Therefore, when you use Python to call the DLL, you will encounter the error: "Error: [WinError 193] %1 is not a valid Win32 application." This error occurs because your Python is the x64 version, whereas the TSMaster.dll is the x86 version. To resolve this issue, you simply need to upgrade TSMaster.

**Comment by lijieamd** [comment]
@sy950915 
Thank you for your detailed information about the problem.
But it's a bit inconvenient for my development environment, which I can't use other version of TSMaster due to some IT policy.
Is there another way to use the x86 version?

**Comment by sy950915** [comment]
Here are the ways you can use it:

1、Change your Python version to use the x86 version of Python.
2、You can also use the COM component method, for which we still provide examples. 
     .\bin\\Data\SDK\examples\COM Automation\OutOfProcess

**Comment by sy950915** [comment]
@lijieamd 
Here are the ways you can use it:

1、Change your Python version to use the x86 version of Python.
2、You can also use the COM component method, for which we still provide examples.
.\bin\Data\SDK\examples\COM Automation\OutOfProcess

**Comment by lijieamd** [comment]
@sy950915 
Thank you! I'll try it.

**Comment by lijieamd** [comment]
@sy950915 
Thank you!
There is a built-in x86 Python in the TSMaster installation folder, I tried this version and it runs the demo successfully.
